package Grafica;

public enum Tipo {
	
	AVIONVIVO,AVIONMUERTO,SATELITEVIVO,SATELITEMUERTO,CIUDADVIVA,CIUDADMUERTA,BASEMILITARVIVA,BASEMILITARMUERTA,EXPLOSIONVIVA,EXPLOSIONMUERTA,MABVIVO,MABMUERTO,MBIVIVO,MBIMUERTO,MISILINTELIGENTEVIVO,MISILINTELIGENTEMUERTO,MISILTONTOVIVO,MISILTONTOMUERTO

}
